version: 2.1

jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: pip install -r requirements.txt
  test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run:  python3 test_board.py
      - run:  python3 test_piece.py
      - run:  python3 test_bot.py

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build