version: 2.1
orbs:
  python: circleci/python@2.0.3
  heroku: circleci/heroku@1.2.6

jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          command: sudo apt-get install python3-pip python3-dev build-essential
      - run: pip install parameterized
  test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run:  python3 test_board.py
      - run:  python3 test_piece.py
      - run:  python3 test_bot.py

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build